// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYD0jYYjF5dwBuRaDIVcSyPAqRgBvG7A',
    appId: '1:457442626452:web:56288522d1409ef06b9d81',
    messagingSenderId: '457442626452',
    projectId: 'jam-logger',
    authDomain: 'jam-logger.firebaseapp.com',
    storageBucket: 'jam-logger.appspot.com',
    measurementId: 'G-W3W9YZE8NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1t2nLa935a73JjFH7Dw2I0nPoVfK5jM4',
    appId: '1:457442626452:android:57d2d57d02ec7c7d6b9d81',
    messagingSenderId: '457442626452',
    projectId: 'jam-logger',
    storageBucket: 'jam-logger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHgGCKwoFV4kbPIcdFYhwRjYB3COLE44',
    appId: '1:457442626452:ios:8dcc5c0f4c43197c6b9d81',
    messagingSenderId: '457442626452',
    projectId: 'jam-logger',
    storageBucket: 'jam-logger.appspot.com',
    iosClientId: '457442626452-2riq1qbidk82coe1oj6topr9b4rtg03l.apps.googleusercontent.com',
    iosBundleId: 'com.cows.are.beautiful.jamLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdHgGCKwoFV4kbPIcdFYhwRjYB3COLE44',
    appId: '1:457442626452:ios:e72a12f727119ee46b9d81',
    messagingSenderId: '457442626452',
    projectId: 'jam-logger',
    storageBucket: 'jam-logger.appspot.com',
    iosClientId: '457442626452-6dc11iih2sivu03agsuf36698666j5aj.apps.googleusercontent.com',
    iosBundleId: 'com.cows.are.beautiful.jamLogger.RunnerTests',
  );
}
